const USER_LOGOUT = 'USER_LOGOUT';
const REQUEST = 'REQUEST';
const SUCCESS = 'SUCCESS';
const FAIL = 'FAIL';
const USER_UPDATE = 'USER_UPDATE';
const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';

export {
  USER_LOGOUT,
  REQUEST,
  SUCCESS,
  FAIL,
  USER_UPDATE,
  RESET_PASSWORD_SUCCESS,
};
