const data = [
  [
    {
      title: 'Xu hướng',
      content: [
        'Samsung Galaxy S20 Plus',
        'Samsung Galaxy A51',
        'Samsung Galaxy M11',
        'Samsung Galaxy A31',
        'Iphone 11',
        'Ipad 10.2',
        'Ipad Mini 5',
        'Samsung Galaxy A11',
        'Samsung Galaxy A20s',
        'iPhone 11 Pro Max 64GB',
        'Vsmart Active 3',
        'Realme 3 Pro',
        'Galaxy Note 10 Plus ',
        'OPPO A9 ',
        'iPhone  SE 64GB',
        'Samsung Galaxy Tab A8',
        'Xiaomi Redmi Note 8',
        'Realme C3i',
        'Realme 5 Pro',
        'VIVO Y91C',
      ],
    },
    {
      title: 'Nổi bật',
      content: [
        'Oppo A31',
        'Oppo A12',
        'Oppo Reno 3',
        'Vsmart Joy 3',
        'Vsmart Star',
        'Vivo Y15',
        'Vivo Y12',
        'Smartphone Chính Hãng',
        'Xiaomi Redmi 8',
        'Samsung',
        'Apple',
        'Oppo',
        'VSmart',
        'Vivo',
        'Xiaomi',
        'Nokia',
        'Realme',
        'Blackberry',
        'Bphone',
      ],
    },
    {
      title: 'Máy tính bảng',
      content: [
        'Phụ kiện điện thoại',
        'Máy đọc sách',
        'Dịch vụ, Chính sách',
        'Trung tâm bảo hành chính hãng',
        'Hướng dẫn mua trả góp',
        'Quy trình đóng gói, giao hàng',
        'Quy trình đổi trả và bảo hành',
      ],
    },
    { title: 'home_menu', content: [] },
  ],
  [
    {
      title: 'Tivi',
      content: [
        'Tivi bán chạy',
        'Tivi mới 2020',
        'Tivi cao cấp',
        'Smart Tivi - Android Tivi',
        'Internet Tivi',
        'Tivi 4K',
        'Tivi LED thường ',
        'Tivi OLED',
        'Tivi QLED',
        'Âm thanh & Phụ kiện',
        'Loa nghe nhạc',
        'Loa Karaoke ',
        'Dàn âm thanh',
        'Android TV Box',
        'Amply',
        'Micro',
        'Đầu CD, DVD, Karaoke',
        'Máy radio cassette',
        'Phụ kiện Tivi',
        'Phụ kiện Âm thanh',
      ],
    },
    {
      title: 'Máy Lạnh- Máy Điều Hòa',
      content: [
        'Máy lạnh bán chạy',
        'Máy lạnh mới 2020',
        'Máy lạnh Inverter',
        'Máy Giặt',
        'Máy giặt bán chạy',
        'Máy giặt mới 2020',
        'Máy giặt Inverter',
        'Máy Sấy Quần Áo',
        'Tủ Lạnh',
        'Tủ lạnh bán chạy',
        'Tủ lạnh mới 2020',
        'Tủ lạnh Side by side',
        'Tủ lạnh Inverter',
        'Tủ Đông - Tủ Mát',
        'Máy Nước Nóng',
        'Máy Rửa Chén',
        'Tủ Ướp Rượu',
      ],
    },
    {
      title: 'Dịch Vụ và Bảo Hành',
      content: [
        'Bảo hành - Đổi trả',
        'TikiNow- Giao Trong Ngày',
        'Lắp Đặt Tận Nhà',
        'Mua Trả góp 0%',
        'Chính Hãng Thương Hiệu ',
        'Samsung',
        'LG',
        'Electrolux',
        'Sony',
        'Daikin',
        'Ariston',
        'TCL',
        'Aqua',
        'Sharp',
        'Hitachi',
        'Mitsubishi',
        'Panasonic',
        'Beko',
        'Ferroli',
        'Sanaky',
        'JBL',
        'Phillips',
      ],
    },
    { title: '', content: [] },
  ],
  [
    {
      title: 'Thiết Bị Âm Thanh',
      content: [
        'Tât Cả Tai nghe',
        'Tai nghe nhét tai',
        'Tai nghe chụp tai',
        'Tai nghe Bluetooth đàm thoại',
        'Tai nghe nhạc Bluetooth',
        'Tai nghe Bluetooth Thể Thao',
        'Tât Cả Loa',
        'Loa Vi Tính',
        'Loa Bluetooth',
        'Loa Kéo',
        'Soundbar/loa hifi/khác',
        'Máy nghe nhạc - Máy Ghi Âm',
        'Phụ Kiện Âm Thanh',
        'Thiết Bị Đeo Thông Minh',
        'Đồng Hồ Thông Minh',
        'Kính Thực Tế Ảo',
        'Thiết bị nhà thông minh',
      ],
    },
    {
      title: 'Phụ Kiện Điện Thoại',
      content: [
        'Pin Sạc Dự Phòng',
        'Dây Cáp Sạc',
        'Cáp sạc iPhone/iPad',
        'Đế Sạc Không Dây',
        'Adapter - Củ sạc',
        'Thẻ nhớ điện thoại',
        'Bao da - Ốp lưng',
        'Miếng dán màn hình',
        'Gậy chụp hình - Gậy Selfie',
        'Sim Số, 3G/4G',
        'Thiết Bị Game',
        'Chuột Gaming',
        'Bàn phím Gaming',
        'Tai nghe Gaming',
        'Lót chuột game - Mousepad',
        'Màn hình Gaming',
        'Ghế Gaming',
        'Tay bấm game - Thiết Bị điều khiển',
        'Máy chơi game - Console',
        'Đĩa Game',
        'Phụ kiện Game',
      ],
    },
    {
      title: 'Thiết Bị Mạng',
      content: [
        'Bộ phát Wifi',
        'Thiết Bị 3G/4G',
        'Router Wifi',
        'Thiết Bị Mở Rộng Sóng',
        'Access Point',
        'Bộ chia mạng - Switch',
        'USB wifi',
        'Ổ cứng mạng',
        'Phụ kiện thiết bị mạng',
        'Thương hiệu nổi bật',
        'Sennheiser',
        'Audio-technica',
        'Energizer',
        'Microlab',
        'SoundMax',
        'TP-Link',
        'Sony',
        'WD',
        'Seagate',
        'Dell',
        'Totolink',
      ],
    },
    { title: '', content: [] },
  ],
  [
    {
      title: 'Dịch Vụ và Bảo Hành',
      content: [
        'TikiNow - Giao Nhanh tận nhà',
        'Trả góp 0%',
        'Chính Hãng 100%',
        'Bảo hành tận nhà',
        'Đổi trả tận nhà',
        'Laptop Theo Giá',
        'Dưới 8 triệu',
        'Từ 8 - 10 triệu',
        'Từ 10 - 15 triệu',
        'Từ 15 - 20 triệu',
        'Trên 20 triệu',
        'Laptop Theo Core',
        'Intel Core i3',
        'Intel Core i5',
        'Intel Core i7',
      ],
    },
    {
      title: 'Laptop Chính Hãng',
      content: [
        'Macbook',
        'Dell',
        'Asus',
        'HP',
        'LG',
        'Lenovo',
        'Acer',
        'MSI',
        'Masstel',
        'Laptop Gaming',
        'Máy tính để bàn',
        'Thiết Bị Văn Phòng',
        'Màn hình máy tính',
        'Máy in - Máy Scan',
        'Máy Chiếu',
        'Mực in',
        'Giấy in',
        'Phần mềm máy tính',
        'Máy hủy tài liệu',
        'Máy chấm công',
        'Máy và thiết bị văn phòng khác',
      ],
    },
    {
      title: 'Phụ kiện, Linh kiện máy tính',
      content: [
        'Chuột máy tính',
        'Bàn Phím',
        'Combo Bàn Phím & Chuột',
        'Ổ cứng di động',
        'USB',
        'Đế tản nhiệt Laptop',
        'Ổ cứng HDD',
        'Ổ cứng SSD',
        'Bo mạch chủ - Mainboard',
        'Card Màn Hình - VGA',
        'Case - Nguồn Máy Tính - Tản Nhiệt',
        'CPU - Bộ Vi Xử Lý',
        'UPS - Bộ Lưu Điện',
        'Sound Card - Card Âm Thanh',
        'HUB USB',
        'Thiết Bị Khác (adapter laptop ...)',
        'Bảng Vẽ - Bút Vẽ',
        ' Ram máy tính',
      ],
    },
    { title: '', content: [] },
  ],
  [
    {
      title: 'Top Bán Chạy Trong Tháng',
      content: [
        'Top Máy Ảnh DSLR Bán Chạy',
        'Top Máy Ảnh Mirrorless Bán Chạy',
        'Top Ống Kính (Lens) Bán Chạy',
        'Top Phụ Kiện Máy Ảnh Bán Chạy',
        'Sản Phẩm Nổi Bật',
        'Máy Ảnh Canon 750D + Lens 18-55 IS STM',
        'Máy Ảnh Canon M10 KIT 15-45mm',
        ' Máy Ảnh Sony Alpha A6000 + 16-50mm',
        'Máy Ảnh Fujifilm X-T20 (24.3MP) + Lens 18-55mm',
        'Máy Ảnh Canon EOS M50 + Kit 15-45mm',
        'Lens Canon 50mm f/1.8 STM',
        'Máy Ảnh- Máy Quay Phim',
        'Máy Ảnh Mirrorless',
        'Máy Ảnh DSLR',
        'Máy Ảnh Du Lịch',
        'Máy Ảnh Chụp Lấy Liền',
        'Máy Quay Phim Sony',
        'Máy Quay Phim Canon',
      ],
    },
    {
      title: 'Ống Kính- Lens',
      content: [
        'Lens Canon',
        'Lens Sony',
        'Lens Fujifilm',
        'Lens Nikon',
        'Lens Sigma',
        'Lens Tamron',
        'Phụ Kiện Theo Máy Ảnh',
        'Thẻ Nhớ Máy Ảnh',
        'Chân Máy Ảnh Tripods & Monopods',
        'Adapter - Ngàm Chuyển',
        'Dây Đeo Máy Ảnh, Máy Quay',
        'Pin Và Sạc Pin',
        'Đèn Flash Và Phụ Kiện',
        'Gimbal-Thiết Bị Chống Rung',
        'Lens Hood',
        'Kính Lọc- Filter',
        'Dụng Cụ Vệ Sinh Máy Ảnh',
        'Phụ Kiện Máy Ảnh - Máy Quay Khác',
        'Balo-Túi Máy Ảnh',
        'Ống Nhòm',
        'Hộp Đựng, Tủ Chống Ẩm',
      ],
    },
    {
      title: 'Camera Giám Sát',
      content: [
        'Action Camera',
        'Máy Bay Camera - Drone',
        'Camera Hành Trình Ô Tô',
        'Camera Quan Sát',
        'Webcam',
        'Thương Hiệu',
        'Canon',
        'Sony',
        'Fujifilm',
        'Nikon',
        'GoPro',
        'Sigma',
        'Tamron',
        'Benro',
        'Wasabi',
        'Godox',
        'Chương Trình Và Chính Sách Ưu Đãi',
        'Chính Hãng Mới 100%',
        'Trung Tâm Bảo Hành Chính Hãng',
        'Hướng Dẫn Mua Trả Góp 0%',
        'Quy Trình Đổi- Trả Và Bảo Hành',
      ],
    },
    { title: '', content: [] },
  ],
  [
    {
      title: 'Khuyến mãi HOT',
      content: [
        'Bán chạy',
        'Giảm giá',
        'Điện gia dụng trả góp 0%',
        'HOT TREND',
        'Top Thương hiệu',
        'Philips',
        'Lock&Lock',
        'Bluestone',
        'Kangaroo',
        'Sunhouse',
        'Sharp',
        'Panasonic',
        'Electrolux',
        'Toshiba',
        'Delonghi',
        'Comet',
        'Nagakawa',
        'Thương hiệu mới',
        'Hafele',
        'Ariete',
        'Teka',
        'Hurom',
      ],
    },
    {
      title: 'Đồ dùng nhà bếp',
      content: [
        'Top bán chạy ',
        'Nồi chiên',
        'Nồi cơm điện',
        'Máy xay-máy ép',
        'Lò vi sóng',
        'Lò nướng điện',
        'Vỉ nướng điện',
        'Bếp các loại',
        'Máy pha cà phê',
        'Máy làm sữa đậu nành',
        'Máy làm tỏi đen',
        'Bình đun siêu tốc',
        'Nồi áp suất',
        'Máy hút khói, khử mùi',
        'Máy đánh trứng',
        'Máy sấy thực phẩm',
        'Bình thủy điện',
        'Siêu sắc thuốc',
        'Máy hút chân không',
        'Máy sấy chén',
        'Xem tất cả',
      ],
    },
    {
      title: 'Thiết bị gia đình',
      content: [
        'Top bán chạy',
        'Bàn ủi - Bàn là',
        'Quạt điện',
        'Thiết bị sưởi ấm',
        'Máy hút bụi',
        'Robot hút bụi',
        'Máy lọc không khí',
        'Máy tạo ẩm',
        'Máy hút ẩm',
        'Máy lọc nước',
        'Cây nước nóng lạnh',
        'Máy may-máy thêu',
        'Máy sấy quần áo',
        'Máy sấy tay',
        'Xem tất cả',
      ],
    },
    { title: '', content: [] },
  ],
  [
    {
      title: 'Nổi bật',
      content: [
        'Bán chạy',
        'Hàng mới',
        'Giảm giá',
        'Khuyến mãi nổi bật trong tháng',
        'Cẩm nang khuyến mãi',
        'Đồ dùng nhà bếp và phòng ăn giá sốc',
        'Chăn drap và nội thất giá sốc',
        'Đồ dùng nhà tắm và sửa chữa giá sốc',
        'Dụng cụ làm bánh',
        'Thương hiệu hàng đầu',
        'Lock&Lock',
        'Duy Tân',
        'Everon',
        'Luminarc',
        'Minh Long',
        'Homeeasy',
        'Sunhouse',
        'Zojirushi',
        'Karcher',
        'Bosch',
        'Philips',
      ],
    },
    {
      title: 'Đồ dùng gia đình',
      content: [
        'Dụng cụ nấu ăn',
        'Cà men, hộp đựng cơm',
        'Hộp đựng thực phẩm',
        'Kệ nhà bếp',
        'Dao và phụ kiện',
        'Bình nước, bình giữ nhiệt',
        'Bộ bình ly',
        'Bộ bình trà',
        'Bình lọc nước',
        'Ly, cốc',
        'Tô chén đĩa',
        'Đồ dùng phòng ngủ',
        'Ga giường, drap',
        'Nệm',
        'Nội thất',
        'Tủ quần áo',
        'Đèn & thiết bị chiếu sáng',
        'Đèn bàn',
        'Bóng đèn',
        'Ổ cắm điện',
        'Dụng cụ vệ sinh',
        'Thiết bị phòng tắm',
      ],
    },
    {
      title: 'Giàn phơi',
      content: [
        'Đồ dùng và thiết bị nhà tắm',
        'Bộ lau nhà',
        'Phụ kiện giặt ủi',
        'Bảo vệ nhà cửa',
        'Thiết bị điều khiển thông minh',
        'Vật phẩm phong thủy',
        'Đồ thờ cúng',
        'Ổn áp, biến áp',
        'Sửa chữa nhà cửa',
        'Máy khoan',
        'Máy xịt rửa',
        'Thang nhôm',
        'Xe đẩy',
        'Dụng cụ diệt chuột, côn trùng',
        'Pin và dụng cụ sạc pin',
        'Trang trí nhà cửa',
        'Nhạc cụ',
        'Ngoài trời & sân vườn',
        'Hoa tươi và cây cảnh',
      ],
    },
    { title: '', content: [] },
  ],
  [
    {
      title: 'THỰC PHẨM',
      content: [
        'Dầu ăn',
        'Đồ hộp',
        'Gia vị',
        'Thực phẩm ăn liền',
        'Thực phẩm chay',
        'Nấu ăn & Làm bánh',
        'Thực phẩm chế biến',
        'BÁNH KẸO',
        'Bánh ',
        'Kẹo',
        'Socola',
        'ĐỒ UỐNG - GIẢI KHÁT',
        'Bia',
        'Đồ uống có gas',
        'Đồ uống không gas',
        'Đồ uống có cồn',
      ],
    },
    {
      title: 'ĐỒ UỐNG - PHA CHẾ',
      content: [
        'Trà',
        'Cà phê',
        'Ngũ cốc - Bột',
        'Sữa nước',
        'Sữa bột',
        'THỰC PHẨM KHÁC',
        'Thực phẩm bổ dưỡng',
        'Thực phẩm hữu cơ',
        'CHĂM SÓC THÚ CƯNG',
        'Chăm sóc chó',
        'Chăm sóc mèo',
        'Chăm sóc cá',
        'CÓ GÌ HOT TRONG THÁNG',
        'Bách Hóa Online - Mua Sắm Liền Tay',
        'Flash sale dành cho BOSS , giá cực HOT',
      ],
    },
    {
      title: 'TOP THƯƠNG HIỆU',
      content: [
        'Acecook',
        'Ân Nam Finefood',
        'Budweiser',
        'Chupa Chups',
        'Coca - Cola',
        'Dutch Lady - Yomost',
        'Heineken',
        'Kinh Đô Mondelez',
        'Knorr',
        "L'angfarm",
        ' Mars',
        'Me-O',
        'Milo',
        ' Neptune',
        'Nescafe',
        'Omachi',
        ' Orion',
        ' Pepsi',
        ' Quaker',
        ' Smart Heart',
        ' TH true Milk',
        ' Việt Ngũ cốc',
      ],
    },
    { title: '', content: [] },
  ],
  [
    {
      title: 'Khuyến mãi HOT',
      content: [
        'Bán chạy',
        'Hàng mới',
        'TÃ - BỈM',
        'Tã dán',
        'Tã quần',
        'SỮA- THỰC PHẨM ĂN DẶM',
        'Thực phẩm ăn dặm cho bé',
        'Sữa cho bé dưới 24 tháng tuổi',
        'Sữa cho bé trên 24 tháng tuổi',
        'Sữa cho bà mẹ mang thai và sau sinh',
        'CHƯƠNG TRÌNH KHUYẾN MÃI TRONG THÁNG',
        'Mẹ săn khuyến mãi',
        'Siêu thị tã bỉm',
        'Bí kíp chăm sóc nhà sạch của mẹ',
        'Đồ chơi & Thời trang cho bé',
        'Hành trình làm mẹ',
        'Thế giới ăn dặm cho bé',
        'Bí kíp chăm sóc mẹ và bé yêu',
      ],
    },
    {
      title: 'ĐỒ CHƠI',
      content: [
        'Lắp ghép, xếp hình',
        'Đồ chơi giáo dục',
        'Đồ chơi gỗ',
        'Đồ chơi mô hình',
        'Búp bê, Thú bông',
        'Đồ chơi vận động',
        'Đồ chơi sơ sinh',
        'Boardgame',
        'Lều, thảm chơi cho bé',
        'THỜI TRANG-PHỤ KIỆN CHO BÉ',
        'Thời trang sơ sinh',
        'Thời trang bé gái',
        'Giày dép bé gái',
        'Thời trang bé trai',
        'Giày dép bé trai',
        'Phụ kiện cho bé',
        'Vali, balo, túi xách',
        'ĐỒ DÙNG CHO MẸ',
        'Máy hút sữa, Túi trữ sữa',
        'Phụ kiện cho mẹ',
        'Thời trang bầu',
        'Phương pháp dân gian',
      ],
    },
    {
      title: 'ĐỒ DÙNG CHO BÉ',
      content: [
        'Bình sữa, bình tập uống',
        'Dụng cụ tập ăn ',
        'Ghế ăn',
        'Thau bô, chậu tắm',
        'Khăn tắm, áo choàng',
        'Khăn giấy ướt',
        'Nôi, giường cũi, võng',
        'Xe đẩy',
        'GIẶT XẢ & TẮM GỘI CHO BÉ',
        'Giặt xả quần áo cho bé',
        'Nước rửa bình ',
        'Sữa tắm, dầu gội cho bé',
        'Phấn, kem dưỡng da, nước hoa cho bé',
        'GIẶT GIŨ & VỆ SINH NHÀ CỬA',
        'Giặt giũ & chăm sóc quần áo',
        'Vệ sinh nhà cửa',
        'Diệt côn trùng',
        'Khăn giấy',
      ],
    },
    { title: 'Quần áo sơ sinh chính hãng', content: [] },
  ],
  [
    {
      title: 'ƯU ĐÃI HOT 49% ',
      content: [
        'Best Seller - Hot không ngờ',
        'New Arrival - Giá dùng thử cực sốc',
        'Brand Day - Thương hiệu chính hãng ** ƯU ĐÃI MỖI NGÀY',
        'ƯU ĐÃI TRONG THÁNG',
        'Hết mụn - Quên lo âu',
        'Make up lung linh 3in1',
        'Tóc đẹp tung tăng',
        'Hương thơm gợi ánh nhìn',
        'Sạch thơm toàn diện',
        'Sức khỏe vàng',
        'Trang điểm',
        'Trang điểm mặt',
        'Trang điểm mắt',
        'Trang điểm môi',
        'Dụng cụ trang điểm',
        'Thiết bị chăm sóc sức khỏe',
        'Dụng cụ theo dõi sức khỏe',
        'Máy massage',
        'Thiết bị y tế',
        'Thực phẩm chức năng',
      ],
    },
    {
      title: 'Chăm sóc da mặt',
      content: [
        'Sữa rửa mặt',
        'Nước hoa hồng',
        'Serum & kem dưỡng',
        'Dưỡng ẩm',
        'Dưỡng trắng',
        'Mặt nạ',
        'Chống nắng',
        'Chăm sóc cơ thể',
        'Sữa tắm',
        'Dưỡng thể',
        'Khử mùi',
        'Chăm sóc tóc',
        'Dầu gội - Dầu xả',
        'Dưỡng tóc - Ủ tóc',
        'Chăm sóc cá nhân',
        'Chăm sóc răng miệng',
        'Dược mỹ phẩm',
        'Sản phẩm thiên thiên',
        'Hỗ trợ tình dục',
        'Thiết bị làm đẹp',
        'Bộ sản phẩm làm đẹp',
        'Nước hoa',
        'Tinh dầu spa',
      ],
    },
    {
      title: 'Thương hiệu',
      content: [
        'La Roche-Posay',
        "L'oreal Paris",
        'Maybelline',
        'Vichy',
        'Laneige',
        ' Innsifree',
        'Rohto',
        'Anessa - Senka - ZA - Tsubaki',
        'Nivea',
        'Ofélia',
        'Durex',
        'SHISEIDO',
        'Mamonde',
        'Omron',
        'Milaganics',
        'DHC',
        'Yves Rocher',
        'P&G',
        'BBIA',
        'Vedette',
        'The Body Shop',
        "Paula's Choice",
        'Romano - Enchanteur - Bioessence',
        'OHUI - Belif ',
      ],
    },
    { title: '', content: [] },
  ],
  [
    {
      title: 'THỜI TRANG NỮ',
      content: [
        'Áo Croptop Nữ',
        'Đầm Dáng Xòe',
        'Áo Khoác Cardigan Nữ',
        'Quần Ống Rộng Nữ',
        'Áo Ngực',
        'GIÀY DÉP NỮ',
        'Giày cao gót',
        'Giày thể thao Nữ',
        'Giày búp bê',
        'Boots Nữ',
        'Dép xỏ ngón',
        'TÚI THỜI TRANG NỮ',
        'Túi Đeo Chéo Nữ',
        'Ví/Bóp Nữ',
        'Túi Tote',
        'Ví Cầm Tay Nữ',
      ],
    },
    {
      title: 'THỜI TRANG NAM',
      content: [
        'Áo Thun Ngắn Tay Không Cổ',
        'Sơ Mi Ngắn Tay',
        'Quần Tây',
        'Áo Hoodies Nam',
        'Đồ Bộ/Đồ Mặc Nhà Nam',
        'GIÀY DÉP NAM',
        'Giày Thể Thao Nam',
        'Giày Lười Nam',
        'Giày Tây',
        'Dép Nam',
        'Boots Nam',
        'Vệ sinh giày',
        'TÚI THỜI TRANG NAM',
        'Túi Đeo Chéo Nam',
        'Ví Nam',
        'Túi xách công sở nam',
        'Ví Nam',
      ],
    },
    {
      title: 'BALO & VALI',
      content: [
        'Balo Nam',
        'Balo Nữ',
        'Cặp, túi chống sốc laptop',
        'Túi Du Lịch',
        'Vali',
        'PHỤ KIỆN',
        'Mắt Kính',
        'Khăn & Tất, Vớ Nữ',
        'Thắt Lưng, Dây Nịt Nữ',
        'Nón Nam',
        'Thắt Lưng, Dây Nịt Nam',
        'Vớ Nam',
      ],
    },
    {
      title: 'ĐỒNG HỒ & TRANG SỨC',
      content: [
        'Đồng Hồ Nam',
        'Đồng Hồ Nữ',
        'Dây Chuyền',
        'Vòng tay',
        'Bông tai',
      ],
    },
  ],
  [
    {
      title: 'HOT',
      content: [
        'Săn hàng thể thao - Giảm đến 50% ',
        'Hoạt động ngoài trời - Giá chỉ từ 99k',
        'Thương hiệu giày thể thao mới ',
        'THƯƠNG HIỆU NỔI BẬT',
        'Anta',
        "Biti's Hunter",
        'Boxing Saigon',
        'Coleman',
        'MDbuddy',
        'Mizuno',
        'Mofit',
        'Naturehike',
        'Nike',
        'Reebok',
        'Salomon',
        'Sportslink',
        'Victorinox',
        'Yonex',
        'Zippo',
        'Li-Ning',
        'Asics',
        'Adidas',
      ],
    },
    {
      title: 'THỜI TRANG THỂ THAO',
      content: [
        'Giày thể thao nam',
        'Giày thể thao nữ',
        'Trang phục thể thao nam',
        'Trang phục thể thao nữ',
        'GYM - YOGA & FITNESS',
        'Máy chạy bộ',
        'Xe đạp tập',
        'Giàn tạ - tạ tập',
        'Xà đơn - xà kép',
        'Thảm yoga, bóng tập',
        'Đấm bốc & võ thuật',
        'Dụng cụ tập bụng',
        'THỰC PHẨM BỔ SUNG NĂNG LƯỢNG',
        'Thực phẩm tăng cân',
        'Thực phẩm tăng cơ',
        'Thực phẩm tăng sức bền',
        'Thực phẩm giảm cân',
        'Bổ sung năng lượng',
      ],
    },
    {
      title: 'HOẠT ĐỘNG DÃ NGOẠI',
      content: [
        'Lều - túi ngủ',
        'Bàn ghế xếp di động',
        'Câu cá',
        'Trượt patin',
        'Phụ kiện dã ngoại',
        'CÁC BỘ MÔN THỂ THAO',
        'Bơi lội',
        'Bóng đá',
        'Bóng rổ',
        'Bóng bàn',
        'Cầu lông',
        'Tennis',
        'PHỤ KIỆN THỂ THAO',
        'Túi thể thao',
        'Băng cổ tay, băng trán thể thao',
        'Bình nước thể thao',
      ],
    },
    { title: '', content: [] },
  ],
  [
    {
      title: 'Mô tô - Xe máy',
      content: [
        'Xe đạp - Xe điện trả góp 0% lãi suất',
        'Chuyên trang xe và phụ kiện ',
        'Xe tay ga',
        'Xe số',
        'Xe côn tay',
        'Xe Mô tô',
        'Xe 50cc',
        'Phụ kiện xe máy',
        'Dầu nhớt, phụ gia',
        'Ô Tô',
        'Hyundai',
        'FORD',
        'Honda',
        'Toyota',
        'Thương hiệu mới (Hot)',
        'Homesheel',
        'Ekokemika',
        'AGU',
        'Focar',
        'Voltronic',
        'Karshine',
        'AGV Helmet',
      ],
    },
    {
      title: 'Xe điện',
      content: [
        'Xe máy điện',
        'Xe đạp điện',
        'Xe điện thăng bằng',
        'Xe đạp',
        'Xe đạp thể thao',
        'Xe đạp thông dụng',
        'Xe đạp Fixed gear',
        'Xe đạp trẻ em',
        'Xe Scooter',
        'Phụ kiện , đồ nghề xe đạp',
        'Mũ bảo hiểm',
        'Mũ bảo hiểm xe máy',
        'Mũ bảo hiểm xe đạp',
        'Máy rửa xe',
        'Phụ kiện ô tô',
        'Gối, đệm, ghế',
        'Nước hoa, sáp thơm',
        'Chắn nắng, bạt phủ xe',
        'Thảm sàn, để chân',
        'Sản phẩm chăm sóc xe',
        'Phụ tùng ô tô',
      ],
    },
    {
      title: 'Thương hiệu',
      content: [
        'Honda',
        'Yamaha',
        ' Vespa/Piaggio',
        'Vinfast',
        'Royal Enfield',
        'Triumph Motorcycle',
        'Asia Helmet',
        'Royal Helmet',
        'Liqui moly',
        'Andes',
        'Motul',
        'Chita',
        'Soft99',
        ' Giant',
        ' 3M',
        ' Michelin',
        ' Pega',
        'Sonax',
        'Bullsone',
        'Philips',
        'Bosch',
        'Fornix',
        'YSS',
      ],
    },
    { title: '', content: [] },
  ],
  [
    {
      title: 'HOT',
      content: [
        'Săn deal từ 99k',
        'Sản phẩm bán chạy',
        'Thương Hiệu Luxury',
        'Ngày hội thương hiệu',
        'XUẤT XỨ',
        'Joybuy',
        'China',
        'Taiwan',
        'Korea',
        'Singapore',
        'US',
        'Úc',
        'Nhật',
        'THƯƠNG HIỆU',
        'Laneige',
        'FILA',
        'Lock&Lock',
        'Oral-B',
        'Xiaomi',
        'Huawei',
        'Naruko',
        'My Beauty Diary',
      ],
    },
    {
      title: 'THIẾT BỊ SỐ - PHỤ KIỆN SỐ',
      content: [
        'Tai nghe',
        'Loa nghe nhạc ',
        'Thiết bị thông minh',
        'NHÀ CỬA - ĐỜI SỐNG',
        'Phòng ăn & nhà bếp',
        'Phòng tắm',
        'Trang trí nhà cửa',
        'LÀM ĐẸP - SỨC KHOẺ',
        'Chăm sóc da mặt',
        'Trang điểm',
        'Thiết bị làm đẹp',
        'ĐIỆN GIA DỤNG',
        'Thiết bị nhà bếp',
        'Thiết bị gia đình',
        'Phụ kiện điện gia dụng ',
        'ĐIỆN THOẠI - MÁY TÍNH BẢNG',
        'Điện thoại thông minh',
        'Máy tính bảng',
        'Điện thoại phổ thông',
      ],
    },
    {
      title: 'SÁCH NGOẠI VĂN - VĂN PHÒNG PHẨM',
      content: [
        "Children's Books",
        'Business & Economics',
        'Văn phòng phẩm',
        'MẸ BÉ',
        'Đồ chơi',
        'Đồ dùng cho bé',
        'Chăm sóc mẹ bầu',
        'LAPTOP - MÁY VI TÍNH',
        'Linh kiện máy tính',
        'Laptop',
        'Máy in - máy scan',
        'MÁY ẢNH - MÁY QUAY PHIM',
        'Phụ kiện máy ảnh',
        'Máy ảnh',
        'Ống kính',
        'THỜI TRANG',
        'Thời trang nữ',
        'Thời trang nam',
        'Túi và phụ kiện',
      ],
    },
    { title: 'Banner', content: [] },
  ],
  [
    {
      title: 'KHUYẾN MÃI HOT',
      content: [
        '1111 deal sốc chỉ 11k',
        'Alphabooks - Giảm đến 50%',
        'Nhã Nam - Giảm đến 50%',
        'Fahasa đọc sách thả ga',
        'Mcbooks - Giảm đến 50%',
        'Đinh Tị -  Giảm đến 70%',
        'Deli - Giảm đến 50%',
        'Sách Ngoại Văn - Mua 1 Tặng 1',
        'Họa Cụ Online - Giảm đến 50%',
        'Văn Phòng Phẩm - Ưu đãi đến 90%',
        'Sổ Tay Các Loại - Giảm đến 49%',
        'TIKI KHUYÊN ĐỌC',
        'Top sách bán chạy 2020',
        'Phiên bản đặc biệt chỉ có tại Tiki',
        'Sách tương tác cho bé',
        'How-to-Self Help',
        "Chosen by Mom's heart",
        'The Light Novel',
      ],
    },
    {
      title: 'SÁCH TIẾNG VIỆT',
      content: [
        'Sách Bán Chạy',
        'Sách Văn Học',
        'Sách Kinh Tế',
        'Sách Kỹ Năng',
        'Sách Thiếu Nhi',
        'Sách Nuôi Dạy Con',
        'Sách Học Ngoại Ngữ',
        'Sách Kiến Thức - Tổng Hợp',
        'SÁCH NGOẠI VĂN',
        'Chỉ từ $1',
        'Must read',
        'New arrival',
        "Children's Books",
        'Fiction',
        'Dictionary',
        'VĂN PHÒNG PHẨM',
        'Sổ Tay Lập Kế Hoạch',
        'Bút - Viết Khuyến Mãi',
        'Bút Lông Màu',
        'Máy Tính Điện Tử',
        'Giấy in - Fax - Photo',
        'Dụng Cụ Học Sinh',
        'Dụng Cụ Văn Phòng',
        'Quà Tặng Tổng Hợp',
      ],
    },
    {
      title: 'CÔNG TY PHÁT HÀNH',
      content: [
        'NXB Trẻ',
        'NXB Kim Đồng',
        'Nhã Nam',
        'Alphabooks',
        'AZ Việt Nam',
        'First News',
        'Đinh Tị',
        'MC Books',
        'Đông A',
        'Huy Hoàng',
        'IPM',
        'Saigonbooks',
        'Thái Hà',
        'DK',
        'Usborne',
        'Hachette',
        'Scholastic',
        'Penguin Random House',
        'Bloomsbury',
        'HarperCollins',
        'Harvard Business Review',
      ],
    },
    { title: '', content: [] },
  ],
  [
    {
      title: 'NẠP THẺ & TIỆN ÍCH',
      content: [
        'Nạp tiền điện thoại',
        'Thẻ game',
        'Thẻ cào điện thoại ',
        'Thẻ 3G/4G',
        'Sim 3G/4G - Bộ phát wifi',
        'Đặt vé máy bay',
        'Phiếu quà tặng Tiki',
        'NHÀ HÀNG - ĂN UỐNG ',
        'Buffet',
        'Nhà hàng - Quán ăn',
        'Cà phê - Kem - Bánh',
      ],
    },
    {
      title: 'SPA - LÀM ĐẸP',
      content: [
        'Chăm sóc da',
        'Massage body, foot',
        'Làm tóc, nail ',
        'Thẩm mỹ viện',
        'Gym, Yoga',
        'SỰ KIỆN GIẢI TRÍ ',
        'Ca nhạc - Phim - Kịch',
        'Vui chơi - Giải trí',
        'Studio - Chụp ảnh ',
        'NHA KHOA - SỨC KHỎE',
        'Nha Khoa',
        'Khám sức khỏe tổng quát',
        'BẢO HIỂM',
        'Bảo hiểm sức khỏe',
        'Bảo hiểm du lịch',
      ],
    },
    {
      title: 'SỰ KIỆN THỂ THAO',
      content: [
        'DU LỊCH - KHÁCH SẠN',
        'Khách sạn - Resort',
        'Tour du lịch',
        'Vé tham quan ',
        'KHÓA HỌC ONLINE',
        'Ngoại ngữ',
        'Kinh doanh - Marketing',
        'Vi tính văn phòng',
        'Thiết kế đồ họa & video',
        'IT và lập trình',
        'Nuôi dạy con',
        'Nghệ thuật',
        'Kế toán - Tài chính - Đầu tư',
      ],
    },
    { title: 'Banner', content: [] },
  ],
];

export default data;
