const categoryTab = [
  {
    link: '/products?category=1789',
    position: '-392px -52px',
    // position: '-392px -75px',
    width: '11px',
    height: '18px',
    label: 'Điện Thoại - Máy Tính Bảng',
  },
  {
    link: '/products?category=4221',
    position: '-229px -181px',
    positionLight: '',
    width: '18px',
    height: '14px',
    label: 'Điện Tử - Điện Lạnh',
  },
  {
    link: '/products?category=1815',
    position: '-331px -317px',
    width: '16px',
    height: '17px',
    label: 'Phụ Kiện - Thiết Bị Số',
  },
  {
    link: '/products?category=1846',
    position: '-203px -181px',
    width: '21px',
    height: '14px',
    label: 'Laptop - Thiết bị IT',
  },
  {
    link: '/products?category=1801',
    position: '-90px -180px',
    width: '18px',
    height: '15px',
    label: 'Máy Ảnh - Quay Phim',
  },
  {
    link: '/products?category=1882',
    position: '-20px -365px',
    width: '15px',
    height: '18px',
    label: 'Điện Gia Dụng',
  },
  {
    link: '/products?category=1883',
    position: '-333px -275px',
    width: '24px',
    height: '14px',
    label: 'Nhà Cửa Đời Sống',
  },
  {
    link: '/products?category=4384',
    position: '-392px 0px',
    width: '12px',
    height: '21px',
    label: 'Hàng Tiêu Dùng - Thực Phẩm',
  },
  {
    link: '/products?category=2549',
    position: '-392px -26px',
    width: '10px',
    height: '21px',
    label: 'Đồ chơi, Mẹ & Bé',
  },
  {
    link: '/products?category=1520',
    position: '-333px -85px',
    width: '19px',
    height: '20px',
    label: 'Làm Đẹp - Sức Khỏe',
  },
  // {
  //   link: '/products?category=10389',
  //   position: '-333px -110px',
  //   width: '21px',
  //   height: '18px',
  //   label: 'Thời trang - Phụ kiện',
  // },
  {
    link: '/products?category=1975',
    position: '-287px -317px',
    width: '17px',
    height: '17px',
    label: 'Thể Thao - Dã Ngoại',
  },
  {
    link: '/products?category=8594',
    position: '-261px -288px',
    width: '24px',
    height: '24px',
    label: 'Xe Máy, Ô tô, Xe Đạp',
  },
  {
    link: '/products?category=17166',
    position: '-242px -317px',
    width: '18px',
    height: '16px',
    label: 'Hàng quốc tế',
  },
  {
    link: '/products?category=8322',
    position: '-21px -340px',
    width: '16px',
    height: '18px',
    label: 'Sách, VPP & Quà Tặng',
  },
  {
    link: '/products?category=11312',
    position: '-128px -255px',
    width: '24px',
    height: '24px',
    label: 'Voucher - Dịch Vụ - Thẻ Cào',
  },
];

const takeCare = [
  {
    name: 'Thực Phẩm Tươi Sống',
    thumbnail_url: '/images/home-takecare/1.jpg',
    id: 44792,
  },
  {
    name: 'Đồ Chơi - Mẹ & Bé',
    thumbnail_url: '/images/home-takecare/2.jpg',
    id: 2549,
  },
  {
    name: 'Điện Thoại - Máy Tính Bảng',
    thumbnail_url: '/images/home-takecare/3.jpg',
    id: 1789,
  },
  {
    name: 'Làm Đẹp - Sức Khỏe',
    thumbnail_url: '/images/home-takecare/4.jpg',
    id: 1520,
  },
  {
    name: 'Điện Gia Dụng',
    thumbnail_url: '/images/home-takecare/5.jpg',
    id: 1882,
  },
  {
    name: 'Thời trang nữ',
    thumbnail_url: '/images/home-takecare/6.jpg',
    id: 931,
  },
  {
    name: 'Thời trang nam',
    thumbnail_url: '/images/home-takecare/7.jpg',
    id: 915,
  },
  {
    name: 'Giày - Dép nữ',
    thumbnail_url: '/images/home-takecare/8.jpg',
    id: 1703,
  },
  {
    name: 'Túi thời trang nữ',
    thumbnail_url: '/images/home-takecare/9.jpg',
    id: 976,
  },
  {
    name: 'Giày - Dép nam',
    thumbnail_url: '/images/home-takecare/10.jpg',
    id: 1686,
  },
  {
    name: 'Túi thời trang nam',
    thumbnail_url: '/images/home-takecare/11.jpg',
    id: 27616,
  },
  {
    name: 'Balo và Vali',
    thumbnail_url: '/images/home-takecare/12.jpg',
    id: 6000,
  },
  {
    name: 'Phụ kiện thời trang',
    thumbnail_url: '/images/home-takecare/13.jpg',
    id: 27498,
  },
  {
    name: 'Đồng hồ và Trang sức',
    thumbnail_url: '/images/home-takecare/14.jpg',
    id: 8371,
  },
  {
    name: 'Laptop - Máy Vi Tính - Linh kiện',
    thumbnail_url: '/images/home-takecare/15.jpg',
    id: 1846,
  },
  {
    name: 'Nhà Cửa - Đời Sống',
    thumbnail_url: '/images/home-takecare/16.jpg',
    id: 1883,
  },
  {
    name: 'Hàng Quốc Tế',
    thumbnail_url: '/images/home-takecare/17.jpg',
    id: 17166,
  },
  {
    name: 'Bách Hóa Online',
    thumbnail_url: '/images/home-takecare/18.jpg',
    id: 4384,
  },
  {
    name: 'Thiết Bị Số - Phụ Kiện Số',
    thumbnail_url: '/images/home-takecare/19.jpg',
    id: 1815,
  },
  {
    name: 'Voucher - Dịch vụ',
    thumbnail_url: '/images/home-takecare/20.jpg',
    id: 11312,
  },
];

const hotkey = [
  { keyword: 'áo khoác nam', background: '#ef5350' },
  { keyword: 'tai nghe bluetooth', background: '#8d6e63' },
  { keyword: 'giày nam', background: '#8d6e63' },
  { keyword: 'áo khoác nữ', background: '#5c6bc0' },
  { keyword: 'áo hoodie nữ', background: '#8d6e63' },
  { keyword: 'bitis hunter', background: '#5c6bc0' },
  { keyword: 'áo hoodie nam', background: '#5c6bc0' },
  { keyword: 'loa bluetooth', background: '#66bb6a' },
  { keyword: 'giày nữ', background: '#5c6bc0' },
  { keyword: 'giày thể thao nữ', background: '#ef5350' },
  { keyword: 'tai nghe', background: '#8d6e63' },
  { keyword: 'nồi chiên không dầu', background: '#ab47bc' },
  { keyword: 'áo len nữ', background: '#ab47bc' },
  { keyword: 'quần jean nam', background: '#66bb6a' },
  { keyword: 'giày thể thao nam', background: '#ff7043' },
  { keyword: 'đồng hồ nam', background: '#8d6e63' },
  { keyword: 'lock and lock', background: '#ab47bc' },
  { keyword: 'bình giữ nhiệt', background: '#ff7043' },
  { keyword: 'áo thun nam', background: '#ff7043' },
  { keyword: 'máy sấy tóc', background: '#ab47bc' },
];

export { categoryTab, takeCare, hotkey };
